spring:
  dubbo:
    application:
      name: dubbo-consume
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.dubbo

  sleuth:
    enabled: true
    sampler:
      probability: 1
    zipkin:
      sender:
        type: web #向kafka发送trace信息
server:
  port: 8082  #应为我这里是将服务起在一台电脑, 和生产者的tomcat端口区分以免冲突