server:
  port: 8760

spring:
  profiles: eureka-serve-02

eureka:
  instance:
    hostname: eureka-serve-02
    instance-id: eureka-serve-02
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-serve-01:8759/eureka/,http://eureka-serve-03:8761/eureka/