server:
  port: 8788

spring:
  application:
    name: service-lucy
  zipkin:
    base-url: http://47.93.183.104:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-serve-01:8761/eureka/

feign:
  hystrix:
    enabled: true